# Change these first
owner: mygameplatform # Your GitHub organization or username, where this repository lives
repo: status # The Name of this repository

sites:
  - name: Website
    url: https://www.mygameplatform.com
  - name: Wiki
    url: https://wiki.mygameplatform.com:1010
  - name: Panel
    url: https://panel.mygameplatform.com
#  - name: MyPanel BETA
#    url: https://user.mygameplatform.com:7779
  - name: Login
    url: https://auth.mygameplatform.com:1020/auth
#  - name: Node 1
#    url: https://node1.mygameplatform.com:8080
#  - name: Node 2
#    url: https://node2.mygameplatform.com:8080

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.mygameplatform.com
  # baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status MyGamePlatform.com
  introTitle: Status of mygameplatform.com
  introMessage: Available services
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
